# Generated by Django 5.2.7 on 2025-11-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_alter_product_options_remove_product_created_at_and_more'),
        ('my_cust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_admin.product'),
        ),
    ]
