# Generated by Django 5.2.7 on 2025-11-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cust', '0002_bookingdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
