# Generated by Django 5.2.7 on 2025-11-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cust', '0003_bookingdetail_alt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
