# Generated by Django 5.2.7 on 2025-11-17 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cust', '0004_bookingdetail_booked_at_bookingdetail_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking'), ('COD', 'Cash on Delivery'), ('Wallet', 'Wallet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
