# Generated by Django 5.2.6 on 2025-10-16 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter the name of the product', max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Enter a detailed explanation of the product', null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of items available in inventory', verbose_name='Stock')),
                ('image', models.ImageField(blank=True, help_text='Upload a product image', null=True, upload_to='products/', verbose_name='Product Image')),
                ('available', models.BooleanField(default=True, help_text='Indicates whether the product is active or not', verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
